apps:

  name: recipes-app-server
  script: ./index.js
  exec_mode: cluster
  instances: 4
  max_memory_restart: 20m
  # restart_delay: 1000
  exp_backoff_restart_delay: 100
  # env_prod:
  #   ENVIROMENT: PRODUCTION
  # env_homolog:
  #   ENVIROMENT: HOMOLOG